name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: testEndThreeTimes
        id: testendthreetimes
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: testEndThreeTimes
          setup-command: ''
          command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
            && gradle test --tests "Prog32Test.testEndThreeTimes"
          timeout: 10
          max-score: 10
      - name: testCase1
        id: testcase1
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: testCase1
          setup-command: ''
          command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
            && gradle test --tests "Prog32Test.testCase1"
          timeout: 10
          max-score: 10
      - name: testCase2
        id: testcase2
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: testCase2
          setup-command: ''
          command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
            && gradle test --tests "Prog32Test.testCase2"
          timeout: 10
          max-score: 10
      - name: testCase3
        id: testcase3
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: testCase3
          setup-command: ''
          command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
            && gradle test --tests "Prog32Test.testCase3"
          timeout: 10
          max-score: 10
      - name: testDefault
        id: testdefault
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: testDefault
          setup-command: ''
          command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
            && gradle test --tests "Prog32Test.testDefault"
          timeout: 10
          max-score: 10
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TESTENDTHREETIMES_RESULTS: "${{steps.testendthreetimes.outputs.result}}"
          TESTCASE1_RESULTS: "${{steps.testcase1.outputs.result}}"
          TESTCASE2_RESULTS: "${{steps.testcase2.outputs.result}}"
          TESTCASE3_RESULTS: "${{steps.testcase3.outputs.result}}"
          TESTDEFAULT_RESULTS: "${{steps.testdefault.outputs.result}}"
        with:
          runners: testendthreetimes,testcase1,testcase2,testcase3,testdefault